spring:
  datasource:
    url: jdbc:mysql://localhost:3306/os
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        "[format_sql]": true
